In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("exported_churn_data.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 21
Columns: 21

In [4]:
# Display first 5 rows

df.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,...,Churn Flag,customer_name,country,state,gender,dob,complaint_date,escalations,csat_score,complaint count
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaN,NaN,13.99,627,...,0,keshav,India,Maharashtra,Male,1982-04-12,NaN,NaN,NaN,NaN
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,...,1,raghav,India,Karnataka,Male,1995-11-23,2024-08-28,Y,10.0,2.0
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaN,NaN,6.99,210,...,0,lalita,India,Delhi,Female,1978-02-15,NaN,NaN,NaN,NaN
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaN,NaN,22.99,1725,...,0,mohan,India,Nagaland,Male,2001-08-30,NaN,NaN,NaN,NaN
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,...,1,mira,India,Delhi,Female,1990-05-05,2024-01-20,Y,20.0,1.0

In [5]:
# Check dataset structure

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     object
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     object
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      object
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
 11  Churn Flag               21 non-null     int64
 12  customer_name            21 non-null     object
 13  country                  21 non-null     object
 14  state                    21 non-null     object
 15  gender                   21 non-null     object
 16  dob                      21 non-null     object
 17  complaint_date           7 non-null      object
 18  escalations              7 non-null      object
 19  csat_score               7 non-null      float64
 20  complaint count          7 non-null      float64
dtypes: float64(3), int64(3), object(15)
memory usage: 3.6+ KB

In [6]:
# Check number of rows and columns

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 21
Number of columns: 21

In [7]:
# Check missing values

missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
customerid                  0
subscription_start_date     0
subscription_type           0
renewal_date                0
plan_type                   0
contract_type               0
cancellation_date          15
cancellation_reason        15
monthly_charges             0
cltv                        0
churn_score                 0
Churn Flag                  0
customer_name               0
country                     0
state                       0
gender                      0
dob                         0
complaint_date             14
escalations                14
csat_score                 14
complaint count            14
dtype: int64

In [8]:
# Calculate missing percentage

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": missing_percentage
})

missing_summary

                         Missing Values  Missing Percentage
customerid                            0            0.000000
subscription_start_date               0            0.000000
subscription_type                     0            0.000000
renewal_date                          0            0.000000
plan_type                             0            0.000000
contract_type                         0            0.000000
cancellation_date                    15           71.428571
cancellation_reason                  15           71.428571
monthly_charges                       0            0.000000
cltv                                  0            0.000000
churn_score                           0            0.000000
Churn Flag                            0            0.000000
customer_name                         0            0.000000
country                               0            0.000000
state                                 0            0.000000
gender                                0            0.000000
dob                                   0            0.000000
complaint_date                       14           66.666667
escalations                          14           66.666667
csat_score                           14           66.666667
complaint count                      14           66.666667

In [9]:
# Check duplicate records

duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

Number of duplicate records: 0

In [10]:
# Check current data types

df.dtypes

customerid                  object
subscription_start_date     object
subscription_type           object
renewal_date                object
plan_type                   object
contract_type               object
cancellation_date           object
cancellation_reason         object
monthly_charges            float64
cltv                         int64
churn_score                  int64
Churn Flag                   int64
customer_name               object
country                     object
state                       object
gender                      object
dob                         object
complaint_date              object
escalations                 object
csat_score                 float64
complaint count            float64
dtype: object

In [11]:
date_columns = [
    "subscription_start_date",
    "renewal_date",
    "cancellation_date",
    "dob",
    "complaint_date"
]

for column in date_columns:
    df[column] = pd.to_datetime(df[column], errors="coerce")

print("Date columns converted successfully.")

Date columns converted successfully.

In [12]:
df[date_columns].dtypes

subscription_start_date    datetime64[ns]
renewal_date               datetime64[ns]
cancellation_date          datetime64[ns]
dob                        datetime64[ns]
complaint_date             datetime64[ns]
dtype: object

In [13]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score',
       'churn_flag', 'customer_name', 'country', 'state', 'gender', 'dob',
       'complaint_date', 'escalations', 'csat_score', 'complaint_count'],
      dtype='object')

In [14]:
# Customers without cancellation have no cancellation reason/date
df["cancellation_reason"] = df["cancellation_reason"].fillna("Not Cancelled")

# Complaint-related fields
df["complaint_count"] = df["complaint_count"].fillna(0)
df["escalations"] = df["escalations"].fillna(0)
df["csat_score"] = df["csat_score"].fillna(0)

In [15]:
print("Missing values after cleaning:")

df.isnull().sum()

Missing values after cleaning:

customerid                  0
subscription_start_date     0
subscription_type           0
renewal_date                0
plan_type                   0
contract_type               0
cancellation_date          15
cancellation_reason         0
monthly_charges             0
cltv                        0
churn_score                 0
churn_flag                  0
customer_name               0
country                     0
state                       0
gender                      0
dob                         0
complaint_date             14
escalations                 0
csat_score                  0
complaint_count             0
dtype: int64

In [16]:
df.to_csv("cleaned_customer_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!